all:


######################## todo include R-light in jar

jars:
	jar cfv citeproclight.jar \
	-C bin \
	bin/org/ecobima/*/*/*.class


loc:
	wc -l \
	src/org/ecobima/*/*/*java


gitaddall:
	git add \
	src
