all:


######################## todo include R-light in jar

jars:
	cd bin; jar cfv ../citeproclight.jar \
	org/ecobima/*/*/*.class


loc:
	wc -l \
	src/org/ecobima/*/*/*java


gitaddall:
	git add \
	src
