all:


######################## todo include R-light in jar

jars:
	jar cfv citeproclight.jar \
	-C bin \
	bin/org/ecobima/*/*/*.class


loc:
	wc -l \
	org/ecobima/*/*/*java


gitaddall:
	git add \
	org/ecobima/*/*.txt \
	org/ecobima/*/*java \
	org/ecobima/*/*/*.csl \
	org/ecobima/*/*/*.ris \
	org/ecobima/*/*/*.bib \
	org/ecobima/*/*/*.txt \
	org/ecobima/*/*/*java 



